spring:
  config:
    import: optional:file:secrets.properties,optional:env
  jackson:
    default-property-inclusion: non_null
  security:
    user:
      name: parent
      password: parent123
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:taskstracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        validator:
          apply_to_ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    async:
      request-timeout: 3600000
notification-service:
  url: ${NOTIFICATION_SERVICE_URL:http://localhost:8081}
server:
  port: ${PORT:8080}