spring:
  jackson:
    default-property-inclusion: non_null
  security:
    user:
      name: parent
      password: parent123
  datasource:
    url: jdbc:postgresql://ep-shy-hall-a87bz5gf-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_WTPr2DF6pbIw
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        validator:
          apply_to_ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    async:
      request-timeout: 3600000
  mail:
    host: smtp.gmail.com
    port: 587
    username: e.shchyrova@gmail.com
    password: "zbeq wbvp ehfo rcgw"
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${PORT:8080}